apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dev
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # MySQL 서비스 포트
      targetPort: 3306  # MySQL 컨테이너의 포트와 일치
  #clusterIP: None  # 클러스터 내에서 사용, 외부 접근 필요 시 NodePort로 설정 가능
  type: ClusterIP
