apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
spec:
  replicas: 1  # MySQL 파드 수
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0  # MySQL 버전
          ports:
            - containerPort: 3306  # MySQL 기본 포트
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: jaehyun1234
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql  # MySQL 데이터가 저장될 경로
            - name: mysql-config-volume
              mountPath: /etc/mysql/my.cnf # my.cnf 파일이 마운트될 경로
              subPath: my.cnf  # ConfigMap에 포함된 my.cnf 파일만 마운트
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim  # PVC 이름
        - name: mysql-config-volume  # MySQL 설정 파일 담는 ConfigMap
          configMap:
            name: mysql-config  # 생성한 ConfigMap 이름
