apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
spec:
  replicas: 1  # MySQL 파드 수
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0  # MySQL 버전
          ports:
            - containerPort: 3306  # MySQL 기본 포트
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: jaehyun1234
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql  # MySQL 데이터가 저장될 경로
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim  # PVC 이름 설정
