apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  namespace: dev
spec:
  selector:
    app: my-backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

