name: Java Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      # Gradlew 실행 파일에 실행 권한 부여
      - name: Permission
        run: chmod +x ./gradlew
      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
      # NCP Container Registry 로그인
      - name: Log in to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_USER }}
          password: ${{ secrets.NCP_PASSWORD }}
      # Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}/my-backend-app:latest