name: Java Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      # Gradlew 실행 파일에 실행 권한 부여
      - name: Permission
        run: chmod +x ./gradlew
      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

