name: Java Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # Gradlew 실행 파일에 실행 권한 부여
      - name: Permission
        run: chmod +x ./gradlew
      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
      # NCP Container Registry 로그인
      - name: Log in to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_USER }}
          password: ${{ secrets.NCP_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}/my-backend-app:latest

      # kubectl 설정
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      # Kubeconfig 파일을 사용하여 클러스터에 접근
      - name: Configure kubectl with Naver Cloud
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Check kubeconfig
        run: cat $HOME/.kube/config

      - name: Check Kubernetes Cluster Access
        run: |
          kubectl get nodes


      # 배포 전에 deployment.yaml에서 IMAGE_PLACEHOLDER를 시크릿 값으로 치환
      - name: Replace image placeholder in deployment file
        run: sed -i 's|IMAGE_PLACEHOLDER|${{ secrets.NCP_CONTAINER_REGISTRY_URL }}|g' deployment.yaml

      # Kubernetes에 Deployment 적용 - Dev 환경에
      - name: Apply Kubernetes Deployment to Dev
        run: |
          kubectl apply -f deployment.yaml --namespace=dev


      

      # Kubernetes에 Service 적용 - Dev 환경에
      - name: Apply Kubernetes Service
        run: |
          export PATH=$HOME/bin:$PATH 
          kubectl apply -f service.yaml --namespace=dev